[tool.poetry]
name = "pptlayout"
version = "0.1.0"
description = "Leverage llm to ameliorate the visual attractiveness of a presentation."
authors = [
    { name = "Tianyu Hu", email = "tianyuhu@mail.ustc.edu.cn"},
    ]
license = "MIT"
readme = "README.md"

[project]
requires-python = "=3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
